# Generated by Django 4.0.3 on 2022-04-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='nombre')),
                ('parentesco', models.CharField(max_length=50, verbose_name='integrante')),
                ('dni', models.IntegerField(verbose_name='dni')),
            ],
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universidad', models.CharField(max_length=100, verbose_name='universidad')),
                ('facultad', models.CharField(max_length=100, verbose_name='facultad')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=50, verbose_name='pais')),
                ('Provincia', models.CharField(max_length=50, verbose_name='provincia')),
                ('horario', models.DateField(verbose_name='horario')),
            ],
        ),
    ]
